# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import field_details


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('duration_minutes', models.IntegerField(null=True)),
                ('occurance', field_details.OccuranceField(choices=[(b'1', 'Daily'), (b'2', 'Weekly'), (b'3', 'Monthly')], max_length=1, null=True)),
                ('days_weekly', field_details.DayOfTheWeekField(choices=[(b'1', 'Monday'), (b'2', 'Tuesday'), (b'3', 'Wednesday'), (b'4', 'Thursday'), (b'5', 'Friday'), (b'6', 'Saturday'), (b'7', 'Sunday')], max_length=1, null=True)),
                ('date_monthly', models.CharField(max_length=2, null=True)),
                ('by_time', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'chore',
            },
        ),
    ]
